### ISSUE TITLE
MUI backdrop applied on user menu in dark mode

### ISSUE THREAD

**Issue by jeffvg** [etn-ccis/blui-react-themes#46]
#### Describe the bug
While running react showcase demo noticed the user menu is applying the backdrop to app in dark mode. Nothing seems to happen in light theme.

#### What is the expected behavior?
backdrop not to be applied
#### What are the steps to reproduce?
1. Run react showcase demo
2. click on theme toggle
3. click on data display category or select user menu from header
4. select and user menu component from user menu card

#### Screenshots or links to minimum reproduction example

https://user-images.githubusercontent.com/37150565/178329558-2d5c8d04-638d-4529-8ee3-feacb8887afd.mov

**Comment by bkarambe** [comment]
There is a backdrop in light mode, but it is transparent. 
@huayunh How should this be styled?

**Comment by huayunh** [comment]
No backdrops for desktop version

https://brightlayer-ui-dev.github.io/patterns/account-menu
